version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    networks:
      - default
    depends_on:
      - neo4j
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./data:/data"
    networks:
      - default
networks:
  default:
